version: "3.8"

services:
  noti1:
    build: .
    container_name: noti1
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.114.30:3308/notidb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      # <<< 중요: Kafka는 29092 사용 (EXTERNAL 리스너) >>>
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 10.0.114.30:29092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: 10.0.114.30:29092
      SPRING_CLOUD_STREAM_BINDINGS_ORDER_SCS_CONSUMER_IN_0_GROUP: noti-scs-group
    restart: unless-stopped

  noti2:
    build: .
    container_name: noti2
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.114.30:3308/notidb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 10.0.114.30:29092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: 10.0.114.30:29092
      SPRING_CLOUD_STREAM_BINDINGS_ORDER_SCS_CONSUMER_IN_0_GROUP: noti-scs-group
    restart: unless-stopped